"""Discover and safely install Coordinator's GitHub Actions workflow."""

from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


WORKFLOW_RELATIVE_PATH = Path(".github/workflows/coordinator.yml")
GENERATED_MARKER = "# Generated by Coordinator."
GITHUB_SLUG = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")

WORKFLOW = f"""{GENERATED_MARKER}
name: Coordinator

on:
  push:
    paths:
      - ".coordination/**"
      - "AGENTS.md"
      - "CLAUDE.md"
      - ".github/workflows/coordinator.yml"
  pull_request:
    paths:
      - ".coordination/**"
      - "AGENTS.md"
      - "CLAUDE.md"
      - ".github/workflows/coordinator.yml"

permissions:
  contents: read

jobs:
  validate-coordination:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Validate coordination files
        run: python .coordination/scripts/validate.py
"""


@dataclass(frozen=True)
class GitHubCIStatus:
    """A serializable view of CI discovery or setup."""

    outcome: str
    workflows: tuple[str, ...]
    github_repository: str | None
    coordinator_configured: bool
    requires_confirmation: bool
    message: str

    def as_dict(self) -> dict[str, object]:
        return {
            "outcome": self.outcome,
            "workflows": list(self.workflows),
            "github_repository": self.github_repository,
            "coordinator_configured": self.coordinator_configured,
            "requires_confirmation": self.requires_confirmation,
            "message": self.message,
        }


def _github_repository(remote: str) -> str | None:
    value = remote.strip()
    prefixes = (
        "git@github.com:",
        "ssh://git@github.com/",
        "https://github.com/",
        "http://github.com/",
    )
    for prefix in prefixes:
        if value.startswith(prefix):
            slug = value.removeprefix(prefix).removesuffix(".git").strip("/")
            return slug if GITHUB_SLUG.fullmatch(slug) else None
    return None


def _origin_repository(repo: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), "remote", "get-url", "origin"],
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return _github_repository(result.stdout) if result.returncode == 0 else None


def _workflow_paths(repo: Path) -> tuple[str, ...]:
    github = repo / ".github"
    directory = github / "workflows"
    if github.is_symlink():
        return ()
    if not directory.is_dir() or directory.is_symlink():
        return ()
    return tuple(
        str(path.relative_to(repo))
        for path in sorted(directory.iterdir())
        if path.is_file()
        and not path.is_symlink()
        and path.suffix.lower() in {".yml", ".yaml"}
    )


def _is_coordinator_workflow(path: Path) -> bool:
    if not path.is_file() or path.is_symlink():
        return False
    try:
        with path.open(encoding="utf-8") as stream:
            return stream.readline().rstrip("\n") == GENERATED_MARKER
    except (OSError, UnicodeError):
        return False


def inspect_github_ci(repo: Path) -> GitHubCIStatus:
    """Report GitHub remote and workflow state without changing the repository."""

    target = repo.resolve()
    workflows = _workflow_paths(target)
    generated = target / WORKFLOW_RELATIVE_PATH
    configured = _is_coordinator_workflow(generated)
    if configured:
        outcome = "configured"
        message = "Coordinator CI is already configured."
    elif workflows:
        outcome = "confirmation_required"
        message = (
            "Existing GitHub Actions workflows were found; choose whether to add "
            "Coordinator CI alongside them."
        )
    else:
        outcome = "available"
        message = "No existing GitHub Actions workflows were found."
    return GitHubCIStatus(
        outcome=outcome,
        workflows=workflows,
        github_repository=_origin_repository(target),
        coordinator_configured=configured,
        requires_confirmation=bool(workflows and not configured),
        message=message,
    )


def _safe_workflow_destination(repo: Path) -> Path:
    github = repo / ".github"
    workflows = github / "workflows"
    destination = repo / WORKFLOW_RELATIVE_PATH
    for path in (github, workflows, destination):
        if path.is_symlink():
            raise ValueError(
                f"refusing to write through symlink: {path.relative_to(repo)}"
            )
    if github.exists() and not github.is_dir():
        raise ValueError(".github exists but is not a directory")
    if workflows.exists() and not workflows.is_dir():
        raise ValueError(".github/workflows exists but is not a directory")
    if destination.exists() and not destination.is_file():
        raise ValueError("Coordinator workflow path exists but is not a regular file")
    return destination


def install_github_ci(repo: Path) -> GitHubCIStatus:
    """Install the generated workflow without overwriting user-owned CI."""

    target = repo.resolve()
    before = inspect_github_ci(target)
    if before.coordinator_configured:
        return before
    destination = _safe_workflow_destination(target)
    if destination.exists():
        raise ValueError(
            ".github/workflows/coordinator.yml already exists and is not "
            "Coordinator-managed"
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=".coordinator-", suffix=".yml", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(WORKFLOW)
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)
    after = inspect_github_ci(target)
    return GitHubCIStatus(
        outcome="installed",
        workflows=after.workflows,
        github_repository=after.github_repository,
        coordinator_configured=True,
        requires_confirmation=False,
        message="Added .github/workflows/coordinator.yml.",
    )


def configure_github_ci(
    repo: Path,
    action: str,
    *,
    interactive: bool | None = None,
) -> GitHubCIStatus:
    """Apply the requested setup policy, prompting only for an existing CI system."""

    if action not in {"auto", "add", "skip"}:
        raise ValueError(f"unsupported GitHub CI action: {action}")
    status = inspect_github_ci(repo)
    if status.coordinator_configured or action == "skip":
        if action == "skip" and not status.coordinator_configured:
            return GitHubCIStatus(
                outcome="skipped",
                workflows=status.workflows,
                github_repository=status.github_repository,
                coordinator_configured=False,
                requires_confirmation=False,
                message="Kept the repository's current CI configuration.",
            )
        return status
    if action == "add" or not status.workflows:
        return install_github_ci(repo)

    should_prompt = sys.stdin.isatty() if interactive is None else interactive
    if should_prompt:
        print("Existing GitHub Actions workflows:")
        for workflow in status.workflows:
            print(f"  {workflow}")
        answer = input("Add Coordinator CI alongside them? [y/N] ").strip().lower()
        if answer in {"y", "yes"}:
            return install_github_ci(repo)
    return status
